name: test
on: 
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true
env:
  test1: abc

jobs:
  first-job:
    env:
      test2: def
    timeout-minutes: 1
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [test, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-latest
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: step 1
        env:
          test3: xyz
        run: echo ${{ env.test1 }} ${{ env.test2 }} ${{ env.test3 }}  
        timeout-minutes: 1  
