name: test
on: 
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  first-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20]
        images: [test, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
          - os: ubuntu-latest
      max-parallel: 2
    steps:
      - name: step 1
        run: echo "test"    
        timeout-minutes: 1  
